### ISSUE TITLE
词库编码解码: 简拼

### ISSUE THREAD

**Issue by ghost** [amzxyz/rime_wanxiang_pro#1]
## 添加 简拼 支持
万	w
象	x
拼	p
音	y

```
#词库解码顺序为：简拼; 全拼拼音;墨奇;鹤形;自然码;简单鹤;仓颉首末;虎码首末;五笔前2
万	w;wan;av;ap;ag,ap;du;ms;fp;dn;	87991
象	x;xiang;du;dn;du,pd,ua;gh;no;wx;qj;	3107
拼	p;pin;fk;fk;fb;jp;qt,qj;ul;ru;	5904
音	y;yin;lo;lo;lo;cc;ya;xy;uj;	13619
```

---

简拼: 打任何字 都只需要输入首字母
我使用 [深蓝词库转换](https://github.com/studyzy/imewlconverter) 成词库
![105930](https://github.com/user-attachments/assets/c6728c69-7301-4a6d-ae91-634009eb596c)

[GBK_准确简拼_固顶字库.txt](https://github.com/user-attachments/files/17127154/GBK_._.txt)

**Comment by amzxyz** [comment]
开启全局首字母简拼何须如此，运算里面加入如下类似的语句即可，与词库格式相关
# - abbrev/^(.).+$/$1/
