### ISSUE TITLE
如何切换输入方案

### ISSUE THREAD

**Issue by z1073** [amzxyz/rime_wanxiang_pro#11]
本人小白，首先感谢amzxyz制作的这个方案，部署后使用体验非常丝滑

有个小问题就是如何切换输入方案，我本人用的是小鹤双拼，我媳妇用的全拼，输入方案切换我暂时是去编辑wanxiang.schema.yaml里的set_shuru_sche值，想问下还有其他简单的例如用热键能切换的方法吗，需要如何设置，情指教下，谢谢！

**Comment by amzxyz** [comment]
这个可以这样操作，将方案文件复制一份改个名字，里面的名字也修改了，然后default里面加一行这个方案，目的就是两个方案并存共用词库，然后可以方案选单

**Comment by z1073** [comment]
感谢回复，我按照思路修改了一下，方案是可以切换了，但是两种方案都变成了全拼，我把第二个方案注释掉再重新部署又变回了双拼，不知道我哪里配置不对
方案设置：
![image](https://github.com/user-attachments/assets/e2e0cecd-8748-4937-bd22-cd13aad09df7)

![image](https://github.com/user-attachments/assets/740e55e5-fe7d-413e-8fcb-9e703cfc15d4)

**Comment by z1073** [comment]
搞定了！主方案把这个启用就可以了
![image](https://github.com/user-attachments/assets/67ed6f59-b417-4f70-a354-e6377b217f82)

**Comment by amzxyz** [comment]
> 搞定了！主方案把这个启用就可以了
> ![image](https://github.com/user-attachments/assets/67ed6f59-b417-4f70-a354-e6377b217f82)
> 
更新了，去更新吧！
