### ISSUE TITLE
如何能够支持模糊音？

### ISSUE THREAD

**Issue by netvolcano** [amzxyz/rime_wanxiang_pro#12]
例如我使用小鹤双拼，我试着在radical_pinyin.schema.yaml文件的algebra_flypy条目下增加了一些模糊音的设置语句：

```yaml
  - derive/([ei])n$/$1ng/            # en => eng, in => ing
  - derive/([ei])ng$/$1n/            # eng => en, ing => in
  - derive/^([zcs])h/$1/             # zh, ch, sh => z, c, s
  - derive/^([zcs])([^h])/$1h$2/     # z, c, s => zh, ch, sh
```

但是在使用过程中发现好像不起作用。特别是在选择候选词的时候。是不是现在还不能支持模糊音？

**Comment by amzxyz** [comment]
# 拼写设定
speller:
# table_translator翻译器，支持自动上屏。例如 “zmhu”可以自动上屏“怎么回事”
#  auto_select: true
#  auto_select_pattern: ^[a-z]+/|^[a-df-zA-DF-Z]\w{3}|^e\w{4}
  # 如果不想让什么标点直接上屏，可以加在 alphabet，或者编辑标点符号为两个及以上的映射
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`/
  # initials 定义仅作为始码的按键，排除 ` 让单个的 ` 可以直接上屏
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"  # 第一位<空格>是拼音之间的分隔符；第二位<'>表示可以手动输入单引号来分割拼音。
  algebra:
    __patch:
      - set_shuru_schema     #拼音转双拼码
      - set_algebra_fuzhu    #辅助码部分
      - mohuyin             #模糊音选择性开启


在这个段落下引入，相关的段落写在下面

mohuyin:
  __append:
    - derive/^z([a-z])/v$1/

**Comment by oflg** [comment]
wanxiang.schema.yaml中设置平翘舌模糊音

```
mohuyin:
  __append:
    # 模糊音 可选择性开启
    - derive/^z([a-z])/v$1/
    - derive/^c([a-z])/i$1/
    - derive/^s([a-z])/u$1/
    - derive/^v([a-z])/z$1/
    - derive/^i([a-z])/c$1/
    - derive/^u([a-z])/s$1/
  ```

正常打字确实有效，但对辅码不起作用（比如`azyucf`打不出`震`）。


在radical_pinyin.schema.yaml中把algebra_flypy内的

```
  - xform/^sh/<v>/
  - xform/^ch/<i>/
  - xform/^zh/<u>/
  - xform/'sh/'<v>/
  - xform/'ch/'<i>/
  - xform/'zh/'<u>/
```

改为

```
  - xform/^sh/<s>/
  - xform/^ch/<c>/
  - xform/^zh/<z>/
  - xform/'sh/'<s>/
  - xform/'ch/'<c>/
  - xform/'zh/'<z>/
```
辅助码才有作用。


请问如何修复？
