### ISSUE TITLE
关于语言模型的咨询

### ISSUE THREAD

**Issue by lizezhigrass** [amzxyz/rime_wanxiang_pro#3]
**抱歉申明：**
先说一声抱歉，我不是反馈方案的issuer，而是针对语言模型进行一些咨询。
我已经进行了多天谷歌检索和修改尝试，但是没能得到答案，所以到这里问问。
**需要咨询的问题：**
请问rime在windows下默认安装已经包含librime-octagram模块了吗？如果没有是否必须自己编译安装？
**咨询的原因：**
语言模型在我的电脑上似乎没有发挥作用（配置中是否开启语言模型输出结果都没有变化）。我尝试自己编译librime-octagram，但小白一枚，最终没能成功！

**Comment by amzxyz** [comment]
是的，小狼毫包含所有组件已经包含三大组件，一个是lua扩展，一个是语言模型，还有一个是联想二次上屏的三个组建，只要按照[配置方式(https://github.com/amzxyz/RIME-LMDG/wiki/%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)  进行配置即可使用
