### ISSUE TITLE
词库编码错误

### ISSUE THREAD

**Issue by expoli** [amzxyz/rime_wanxiang_pro#4]
在昨天的 commit 中，有一些词汇的编码有问题，比如
1. ![image](https://github.com/user-attachments/assets/88e56c03-6591-465e-9c41-b4473218c64e)
2. lo ji逻辑的ji拼音有问题
![image](https://github.com/user-attachments/assets/673f582e-d96c-4e64-b473-3b363fcd2e9e)
![image](https://github.com/user-attachments/assets/70bca427-2d31-4e59-bbab-1d997a2b1f90)
![image](https://github.com/user-attachments/assets/2a3625ba-7a1c-4fe8-bb9b-f90f92bb6c50)
3. 会有这部分有问题
![image](https://github.com/user-attachments/assets/9a1d663f-53df-4780-91e3-9b3a1e2ab009)
![image](https://github.com/user-attachments/assets/59f80e2c-d73c-47db-bb2f-d523fa6ea4ca)
![image](https://github.com/user-attachments/assets/ec55cbdf-2815-4e91-84c7-fab4109d862d)

4. 乱码
![image](https://github.com/user-attachments/assets/801a5618-ae50-4527-abe0-0cfd4f6782fe)
![image](https://github.com/user-attachments/assets/782248e1-f016-4897-9dc8-ecb03b400fa5)
![image](https://github.com/user-attachments/assets/8f295548-43f9-49ac-810c-ddf6eff28d7c)
![image](https://github.com/user-attachments/assets/c768828a-49aa-4d61-b2a3-a70bd6f86722)

5. 单字，很多未找到
![image](https://github.com/user-attachments/assets/c69dade4-d853-45ab-93b5-52021d4e1a19)
![image](https://github.com/user-attachments/assets/5e69c703-3f54-4fff-8a2d-817952908bd1)
![image](https://github.com/user-attachments/assets/b02027c1-07e2-4cc1-92d3-03461d4d0d9b)

**Comment by amzxyz** [comment]
逻辑专门修正为轻声
会有的问题昨天已经修复等待上传
单字生僻字本来是没有标准的汉语读音，标记为未找到是因为我们去可以通过反查打出这个字，而在声调的部分正好显示未找到来提示无拼音

乱码的问题不清楚是我哪个工具导致的每次会带出一些，好在量少最后手动修复
