### ISSUE TITLE
cn_dicts的位置能不能自定义

### ISSUE THREAD

**Issue by cnus9** [amzxyz/rime_wanxiang_pro#5]
目前，cn_dicts文件夹须与wanxiang.schema.yaml在同一目录下，如果挪动会导致打字时中文不能上屏，修改wanxiang.dict.yaml文件也是无效的，但en_dicts、jm_dicts可以挪动，其路径可以由修改wanxiang.schema.yaml文件来实现。想请教下，如果想改动cn_dicts文件夹的位置，也就是使该文件夹不必须与wanxiang.schema.yaml保存在同一目录下，需要修改哪个文件中的参数或者通过什么方式来实现？谢谢

**Comment by amzxyz** [comment]
只能在rime用户目录下，没能理解你说的挪动是要挪动到哪里去

**Comment by amzxyz** [comment]
可以的你可以将文件夹加上对应的前缀，然后对不同方案的词库集合进行修改，wanxiang.dict.yaml，指向对应的文件夹即可，其他方案同理，对于万象还要考虑lua中的超级注释模块调用了原来cn_dicts路径，你需要编辑lua将路径一并改成你想要的，同理每个项目都可能存在对路径的多次复用。
