### ISSUE TITLE
这是校对薄荷拼音地球拼音多音词的文件，不知道能不能帮到你

### ISSUE THREAD

**Issue by Jian787** [amzxyz/rime_wanxiang_pro#7]
我看万象拼音的词库里多音词和多音字还有不少错误。这是我之前帮薄荷拼音 https://github.com/Mintimate/oh-my-rime 里的“地球拼音-薄荷定制”维护词库里的多音词时做的列表。除了多音词外，当时还顺便维护了包含多音字“重”的常用词，来测试一下工作量。希望可以帮到你，在维护词库里的多音词时作参考。

“地球拼音-薄荷定制”用的词库是以白霜词库为基础，用自动注音程序给词重新设置发音和声调（这个我也不懂，我不是程序员）。格式是地球拼音的格式：在全拼的后面加上12345表示四声和轻声。这个列表的前半段是词库里有错需要改正的多音词，后半段是有错需要改正的含多音字“重”的词。对于全拼相同而声调不同的多音词，则会有3行，比如“教授”：
教授	jiao shou4	32721
教授	jiao1 shou4	9816
教授	jiao4 shou4	22904

后两行是两种不同的声调，分别有不同的词频。第一行则是两者的词频之和，且“教”字只有全拼jiao没有声调。这样做是为了保证用户在输入jiao shou而没有输入声调时，“教授”两个汉字对应的词频是“教授	jiao1 shou4	9816”和“教授	jiao4 shou4	22904”的词频之和。“地球拼音-薄荷定制”里的单字表里的多音字也是这样处理的。

[terra_rime_ice.base常见多音词校对和多音字“重”校对列表.txt](https://github.com/user-attachments/files/18229894/terra_rime_ice.base.txt)

**Comment by amzxyz** [comment]
感谢你的数据文件，我在加速修订词库读音，错误每天都在减少，他将会成为最好的词库
