### ISSUE TITLE
无法输入 【有】

### ISSUE THREAD

**Issue by yibie** [amzxyz/rime_wanxiang_pro#8]
输入 yb
找不到【有】这个字

**Comment by amzxyz** [comment]
没有问题啊？

**Comment by yibie** [comment]
可以在长句输入里输出，但单字里没有：

 
![PixPin_2024-12-24_23-31-16](https://github.com/user-attachments/assets/e3c06283-7a29-42da-93dd-1055dc36b1cd)

**Comment by amzxyz** [comment]
不要乱按ctrl d 进lua第一个文件夹打开文件释放出来!

**Comment by yibie** [comment]
啊？？？

**Comment by yibie** [comment]
我重新 pull 了一遍，然后 deploy 了一遍。 
的，有，这两个基础单字，在单独输入双拼时，确实不在候选栏里，看上去不是我的操作问题。

麻烦大佬检查一下，谢谢！

**Comment by amzxyz** [comment]
你好没有问题

**Comment by yibie** [comment]
我又检查了一遍，发现应该是将之前 [rime_wanxiang_zrm](https://github.com/amzxyz/rime_wanxiang_zrm) 里的文件与 wanxiang_pro 的文件混在一起，放在 Rime 的配置文件夹里，导致的混乱。

已经排查问题，感谢开发这么有用的工具。
